package burp.ui;

import burp.Hackvertor;
import burp.JTabbedPaneClosable;
import burp.Utils;
import burp.tag.Tag;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import java.awt.*;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;

public class ExtensionPanel {

    private int tabCounter = 1;

    private JPanel rootPanel;
    private JTabbedPaneClosable tabbedPanel;
    private HackvertorPanel hackvertorPanel;
    private Hackvertor hackvertor;

    public ExtensionPanel(Hackvertor hackvertor) {
        this.hackvertor = hackvertor;
        $$$setupUI$$$();
        setupUI();
        tabbedPanel.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                if (tabbedPanel.getSelectedIndex() == -1) {
                    return;
                }
                if (tabbedPanel.clickedDelete) {
                    tabbedPanel.clickedDelete = false;
                    if (tabbedPanel.getTabCount() > 1) {
                        if (tabbedPanel.getSelectedIndex() == tabbedPanel.getTabCount() - 1) {
                            tabbedPanel.setSelectedIndex(tabbedPanel.getTabCount() - 2);
                        }
                        return;
                    }
                }
                if (tabbedPanel.getTitleAt(tabbedPanel.getSelectedIndex()).equals("...")) {
                    tabCounter++;
                    tabbedPanel.remove(tabbedPanel.getSelectedIndex());
                    HackvertorPanel hackvertorPanel = new HackvertorPanel(hackvertor);
                    tabbedPanel.addTab(tabCounter + "", hackvertorPanel.$$$getRootComponent$$$());
                    tabbedPanel.addTab("...", new JPanel());
                    tabbedPanel.setSelectedIndex(tabbedPanel.getTabCount() - 2);
                }
            }
        });
    }

    private void setupUI() {
        ComponentAdapter componentAdapter = new ComponentAdapter() {
            @Override
            public void componentShown(ComponentEvent e) {
                if (tabbedPanel.getSelectedIndex() == -1) {
                    return;
                }
                HackvertorPanel selectedPanel = (HackvertorPanel) tabbedPanel.getComponentAt(tabbedPanel.getSelectedIndex());
                selectedPanel.readClipboardAndDecode();
            }
        };
        tabbedPanel.addComponentListener(componentAdapter);
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        rootPanel = new JPanel();
        rootPanel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        tabbedPanel = new JTabbedPaneClosable();
        rootPanel.add(tabbedPanel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        tabbedPanel.addTab("1", panel1);
        panel1.add(hackvertorPanel.$$$getRootComponent$$$(), new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        tabbedPanel.addTab("...", panel2);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
        hackvertorPanel = new HackvertorPanel(hackvertor);

    }

    public void refresh() {
        int index = tabbedPanel.getSelectedIndex();
        if (index == -1) {
            return;
        }
        HackvertorPanel selectedPanel = (HackvertorPanel) tabbedPanel.getComponentAt(index);
        JTabbedPane tabs = selectedPanel.getTabs();
        int tabIndex = tabs.getSelectedIndex();
        String text = tabs.getTitleAt(tabIndex);
        if (text.equals("Custom")) {
            tabs.setComponentAt(tabIndex, Utils.createButtons(hackvertor.getTags(), selectedPanel.getInputArea(), Tag.Category.Custom, null, false));
        }
    }

    public HackvertorPanel addNewPanel() {
        HackvertorPanel panel = new HackvertorPanel(hackvertor);
        tabCounter++;
        tabbedPanel.insertTab(String.valueOf(tabCounter), null, panel.$$$getRootComponent$$$(), null, tabbedPanel.getTabCount() - 1);
        tabbedPanel.setSelectedIndex(tabbedPanel.getTabCount() - 2);
        return panel;
    }

    public void makeActiveBurpTab() {
        JComponent c = rootPanel;
        while (!(c instanceof JTabbedPane)) {
            c = (JComponent) c.getParent();
        }
        JTabbedPane tabbedPane = (JTabbedPane) c;
        tabbedPane.setSelectedComponent(this.rootPanel);
    }
}
